export const FETCH_SKILLS = 'FECTH_SKILLS';
export const FETCH_SKILLS_SUCCESS = 'FETCH_SKILLS_SUCCESS';
export const FETCH_SKILLS_FAIL = 'FETCH_SKILLS_FAIL';

export const ADD_SKILL = 'ADD_SKILL';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_FAIL = 'ADD_SKILL_FAIL';

export const DELETE_SKILL = 'DELETE_SKILL';
